<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="commands" nsURI="http://v8.1c.ru/8.3/debugger/debugDBGUICommands" nsPrefix="commands">
  <eClassifiers xsi:type="ecore:EClass" name="DBGUIExtCmdInfoBase">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="DBGUIExtCmdInfoBase"/>
      <details key="kind" value="elementOnly"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cmdIDNum" unique="false">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="cmdIDNum"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cmdID" unique="false" eType="//DBGUIExtCmds" unsettable="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="cmdID"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="targetIDStr" unique="false">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="targetIDStr"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="v8.1c.ru.8.3.debugger.debugBaseData.ecore#//DebugTargetIdStr"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetID" containment="true" resolveProxies="false">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="targetID"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
      <eType xsi:type="ecore:EClass" href="v8.1c.ru.8.3.debugger.debugBaseData.ecore#//DebugTargetId"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="requestQueueID" unique="false">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="requestQueueID"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DBGUIExtCmdInfoCallStackFormed" eSuperTypes="//DBGUIExtCmdInfoBase">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="DBGUIExtCmdInfoCallStackFormed"/>
      <details key="kind" value="elementOnly"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stopByBP" unique="false" lowerBound="1" unsettable="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="stopByBP"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="suspendedByOther" unique="false" lowerBound="1" unsettable="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="suspendedByOther"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="callStack" upperBound="-1" containment="true" resolveProxies="false">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="callStack"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
      <eType xsi:type="ecore:EClass" href="v8.1c.ru.8.3.debugger.debugBaseData.ecore#//StackItemViewInfoData"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DBGUIExtCmdInfoCorrectedBP" eSuperTypes="//DBGUIExtCmdInfoBase">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="DBGUIExtCmdInfoCorrectedBP"/>
      <details key="kind" value="elementOnly"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bpWorkspace" lowerBound="1" containment="true" resolveProxies="false">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="bpWorkspace"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
      <eType xsi:type="ecore:EClass" href="v8.1c.ru.8.3.debugger.debugBreakpoints.ecore#//BPWorkspaceInternal"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DBGUIExtCmdInfoErrorViewInfo" eSuperTypes="//DBGUIExtCmdInfoBase">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="DBGUIExtCmdInfoErrorViewInfo"/>
      <details key="kind" value="elementOnly"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="requestConnection" unique="false" lowerBound="1" defaultValueLiteral="false" unsettable="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="requestConnection"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="addTargetIDStr" unique="false" upperBound="-1">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="addTargetIDStr"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="v8.1c.ru.8.3.debugger.debugBaseData.ecore#//DebugTargetIdStr"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="addTargetID" upperBound="-1" containment="true" resolveProxies="false">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="addTargetID"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
      <eType xsi:type="ecore:EClass" href="v8.1c.ru.8.3.debugger.debugBaseData.ecore#//DebugTargetId"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="errorInfo" upperBound="-1" containment="true" resolveProxies="false">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="errorInfo"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
      <eType xsi:type="ecore:EClass" href="http://v8.1c.ru/8.3/debugger/debugRTEInfo#//ErrorViewInfoData"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DBGUIExtCmdInfoExprEvaluated" eSuperTypes="//DBGUIExtCmdInfoBase">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="DBGUIExtCmdInfoExprEvaluated"/>
      <details key="kind" value="elementOnly"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="evalExprResBaseData" lowerBound="1" containment="true" resolveProxies="false">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="evalExprResBaseData"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
      <eType xsi:type="ecore:EClass" href="v8.1c.ru.8.3.debugger.debugCalculations.ecore#//CalculationResultBaseData"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DBGUIExtCmdInfoMeasure" eSuperTypes="//DBGUIExtCmdInfoBase">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="DBGUIExtCmdInfoMeasure"/>
      <details key="kind" value="elementOnly"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="measureStr" unique="false">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="measureStr"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2003/XMLType#//Base64Binary"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="measure" containment="true" resolveProxies="false">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="measure"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
      <eType xsi:type="ecore:EClass" href="http://v8.1c.ru/8.3/debugger/debugMeasure#//PerformanceInfoMain"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DBGUIExtCmdInfoQuit" eSuperTypes="//DBGUIExtCmdInfoBase">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="DBGUIExtCmdInfoQuit"/>
      <details key="kind" value="elementOnly"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DBGUIExtCmdInfoRte" eSuperTypes="//DBGUIExtCmdInfoBase">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="DBGUIExtCmdInfoRte"/>
      <details key="kind" value="elementOnly"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="exception" lowerBound="1" containment="true" resolveProxies="false">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="exception"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
      <eType xsi:type="ecore:EClass" href="http://v8.1c.ru/8.1/data/core#//GenericException"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="callStack" upperBound="-1" containment="true" resolveProxies="false">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="callStack"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
      <eType xsi:type="ecore:EClass" href="v8.1c.ru.8.3.debugger.debugBaseData.ecore#//StackItemViewInfoData"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DBGUIExtCmdInfoRteBPCondition" eSuperTypes="//DBGUIExtCmdInfoBase">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="DBGUIExtCmdInfoRteBPCondition"/>
      <details key="kind" value="elementOnly"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="errorInfo" lowerBound="1" containment="true" resolveProxies="false">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="errorInfo"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
      <eType xsi:type="ecore:EClass" href="http://v8.1c.ru/8.3/debugger/debugRTEInfo#//CheckBPCondErrorInfo"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DBGUIExtCmdInfoValueModifyResult" eSuperTypes="//DBGUIExtCmdInfoBase">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="DBGUIExtCmdInfoValueModifyResult"/>
      <details key="kind" value="elementOnly"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="processed" unique="false" lowerBound="1" defaultValueLiteral="true" unsettable="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="processed"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="newValState" containment="true" resolveProxies="false">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="newValState"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
      <eType xsi:type="ecore:EClass" href="v8.1c.ru.8.3.debugger.debugCalculations.ecore#//CalculationResultBaseData"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="errorStr" unique="false">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="errorStr"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2003/XMLType#//Base64Binary"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DBGUIExtCmdShowMetadataObject" eSuperTypes="//DBGUIExtCmdInfoBase">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="DBGUIExtCmdShowMetadataObject"/>
      <details key="kind" value="elementOnly"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metadataObjectName" unique="false">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="metadataObjectName"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DBGUIExtCmdInfoStarted" eSuperTypes="//DBGUIExtCmdInfoBase">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="DBGUIExtCmdInfoStarted"/>
      <details key="kind" value="elementOnly"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DBGUIExtCmdInfoForegroundHelperRequest" eSuperTypes="//DBGUIExtCmdInfoBase">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="DBGUIExtCmdInfoForegroundHelperRequest"/>
      <details key="kind" value="elementOnly"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="senderID" unique="false">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="senderID"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="http://v8.1c.ru/8.1/data/core#//UUID"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DBGUIExtCmdInfoForegroundHelperSet" eSuperTypes="//DBGUIExtCmdInfoBase">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="DBGUIExtCmdInfoForegroundHelperSet"/>
      <details key="kind" value="elementOnly"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="data" containment="true" resolveProxies="false">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="data"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
      <eType xsi:type="ecore:EClass" href="http://v8.1c.ru/8.3/debugger/debugForegroundData#//ForegroundWindowData"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DBGUIExtCmdInfoForegroundHelperProcess" eSuperTypes="//DBGUIExtCmdInfoBase">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="DBGUIExtCmdInfoForegroundHelperProcess"/>
      <details key="kind" value="elementOnly"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="data" containment="true" resolveProxies="false">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="data"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
      <eType xsi:type="ecore:EClass" href="http://v8.1c.ru/8.3/debugger/debugForegroundData#//ForegroundWindowData"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DBGUIExtCmds">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="DBGUIExtCmds"/>
    </eAnnotations>
    <eLiterals name="unknown"/>
    <eLiterals name="targetStarted" value="1"/>
    <eLiterals name="targetQuit" value="2"/>
    <eLiterals name="correctedBP" value="3"/>
    <eLiterals name="rteProcessing" value="4"/>
    <eLiterals name="rteOnBPConditionProcessing" value="5"/>
    <eLiterals name="measureResultProcessing" value="6"/>
    <eLiterals name="callStackFormed" value="7"/>
    <eLiterals name="exprEvaluated" value="8"/>
    <eLiterals name="valueModified" value="9"/>
    <eLiterals name="errorViewInfo" value="10"/>
    <eLiterals name="ForegroundHelperSet" value="11"/>
    <eLiterals name="ForegroundHelperRequest" value="12"/>
    <eLiterals name="ForegroundHelperProcess" value="13"/>
    <eLiterals name="showMetadataObject" value="14"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DBGUIExtCmdsObject">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="DBGUIExtCmds:Object"/>
      <details key="baseType" value="DBGUIExtCmds"/>
    </eAnnotations>
  </eClassifiers>
</ecore:EPackage>
