<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="model" nsURI="http://g5.1c.ru/v8/dt/aggregates" nsPrefix="aggregates">
  <eClassifiers xsi:type="ecore:EClass" name="AccumulationRegisterAggregates">
    <eSuperTypes href="http://g5.1c.ru/v8/dt/metadata/mdclass#//AbstractAggregates"/>
    <eOperations name="validate" unique="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eParameters name="diagnostics" unique="false">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain"/>
      </eParameters>
      <eParameters name="context" unique="false">
        <eGenericType>
          <eTypeArguments>
            <eClassifier xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
          </eTypeArguments>
          <eTypeArguments>
            <eClassifier xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
          </eTypeArguments>
          <eClassifier xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EMap"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aggregates" upperBound="-1" eType="//AccumulationRegisterAggregate" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AccumulationRegisterAggregate">
    <eOperations name="validate" unique="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eParameters name="diagnostics" unique="false">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain"/>
      </eParameters>
      <eParameters name="context" unique="false">
        <eGenericType>
          <eTypeArguments>
            <eClassifier xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
          </eTypeArguments>
          <eTypeArguments>
            <eClassifier xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
          </eTypeArguments>
          <eClassifier xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EMap"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" unique="false" lowerBound="1" eType="//Uuid"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="use" unique="false" lowerBound="1">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/common#//AccumulationRegisterAggregateUse"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="periodicity" unique="false" lowerBound="1">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/common#//AccumulationRegisterAggregatePeriodicity"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dimensions" upperBound="-1">
      <eType xsi:type="ecore:EClass" href="http://g5.1c.ru/v8/dt/metadata/mdclass#//AccumulationRegisterDimension"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Uuid" instanceClassName="java.util.UUID"/>
</ecore:EPackage>
