<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="type" nsURI="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type" nsPrefix="mdclassExtensionType">
  <eClassifiers xsi:type="ecore:EEnum" name="MdPropertyType">
    <eLiterals name="Normal"/>
    <eLiterals name="Checkable"/>
    <eLiterals name="Extensible"/>
    <eLiterals name="CheckableOrExtensible"/>
    <eLiterals name="CheckableOrNotify"/>
    <eLiterals name="MultiState"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="MdPropertyState">
    <eLiterals name="None"/>
    <eLiterals name="Checked"/>
    <eLiterals name="Extended"/>
    <eLiterals name="Notify"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PredefinedItemPropertyState">
    <eLiterals name="Native"/>
    <eLiterals name="AdoptedCheck"/>
    <eLiterals name="AdoptedNotify"/>
  </eClassifiers>
</ecore:EPackage>
