<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="model" nsURI="http://g5.1c.ru/v8/dt/lcore" nsPrefix="core">
  <eClassifiers xsi:type="ecore:EClass" name="BasicType" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanType" eSuperTypes="//BasicType"/>
  <eClassifiers xsi:type="ecore:EClass" name="StringType" eSuperTypes="//BasicType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="length" unique="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fixed" unique="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NumberType" eSuperTypes="//BasicType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="precision" unique="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="scale" unique="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nonNegative" unique="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DateType" eSuperTypes="//BasicType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dateFractions" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/mcore#//DateFractions"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NullType" eSuperTypes="//BasicType"/>
</ecore:EPackage>
