<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:ns1="http://v8.1c.ru/8.1/data-composition-system/core" xmlns:tns="http://v8.1c.ru/8.1/data-composition-system/common" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://v8.1c.ru/8.1/data-composition-system/common" attributeFormDefault="unqualified" elementFormDefault="qualified">
	<xs:import namespace="http://v8.1c.ru/8.1/data-composition-system/core"/>
	<xs:simpleType name="DataCompositionAccountingBalanceType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="None"/>
			<xs:enumeration value="Debit"/>
			<xs:enumeration value="Credit"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="DataCompositionAreaTemplateType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Header"/>
			<xs:enumeration value="Footer"/>
			<xs:enumeration value="HierarchicalHeader"/>
			<xs:enumeration value="HierarchicalFooter"/>
			<xs:enumeration value="OverallHeader"/>
			<xs:enumeration value="OverallFooter"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="DataCompositionBalanceType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="None"/>
			<xs:enumeration value="OpeningBalance"/>
			<xs:enumeration value="ClosingBalance"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="DataCompositionPeriodType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Main"/>
			<xs:enumeration value="Specify"/>
			<xs:enumeration value="Additional"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="Expression">
		<xs:restriction base="xs:string"/>
	</xs:simpleType>
	<xs:complexType name="DataSetFieldRole">
		<xs:sequence>
			<xs:element name="periodNumber" type="xs:integer" minOccurs="0"/>
			<xs:element name="periodType" type="tns:DataCompositionPeriodType" minOccurs="0"/>
			<xs:element name="dimension" type="xs:boolean" minOccurs="0"/>
			<xs:element name="parentDimension" type="xs:string" minOccurs="0"/>
			<xs:element name="account" type="xs:boolean" minOccurs="0"/>
			<xs:element name="accountTypeExpression" type="xs:string" minOccurs="0"/>
			<xs:element name="balance" type="xs:boolean" minOccurs="0"/>
			<xs:element name="balanceGroupName" type="xs:string" minOccurs="0"/>
			<xs:element name="balanceType" type="tns:DataCompositionBalanceType" minOccurs="0"/>
			<xs:element name="accountingBalanceType" type="tns:DataCompositionAccountingBalanceType" minOccurs="0"/>
			<xs:element name="accountField" type="xs:string" minOccurs="0"/>
			<xs:element name="ignoreNullValues" type="xs:boolean" minOccurs="0"/>
			<xs:element name="required" type="xs:boolean" minOccurs="0"/>
			<xs:element name="dimensionAttribute" type="xs:boolean" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="OrderExpression">
		<xs:sequence>
			<xs:element name="expression" type="xs:string"/>
			<xs:element name="orderType" type="ns1:DataCompositionSortDirection" minOccurs="0"/>
			<xs:element name="autoOrder" type="xs:boolean" default="false" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>