<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="model" nsURI="http://g5.1c.ru/v8/dt/geographicalschema" nsPrefix="geographicalSchema">
  <eClassifiers xsi:type="ecore:EClass" name="ShapeCoordinateSystemInfo">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" unique="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="datumName" unique="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="spheroidName" unique="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="semimajorAxis" unique="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="semiminorAxis" unique="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="inverseFlattening" unique="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="angularUnitName" unique="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="radiansPerUnit" unique="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="primeMeridianName" unique="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="primeMeridianLongitude" unique="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataSeriesItem">
    <eOperations name="getDisplayedName" unique="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="objectID" unique="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="figureBaseColor" containment="true" resolveProxies="false">
      <eType xsi:type="ecore:EClass" href="http://g5.1c.ru/v8/dt/mcore#//Color"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="textColor" containment="true" resolveProxies="false">
      <eType xsi:type="ecore:EClass" href="http://g5.1c.ru/v8/dt/mcore#//Color"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="textFont" containment="true" resolveProxies="false">
      <eType xsi:type="ecore:EClass" href="http://g5.1c.ru/v8/dt/mcore#//Font"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" containment="true" resolveProxies="false">
      <eType xsi:type="ecore:EClass" href="http://g5.1c.ru/v8/dt/mcore#//Value"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" unique="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" unique="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="format" unique="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="showMode" unique="false" eType="//LayerSeriesShowMode"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="group" unique="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="textAngle" unique="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="drawingMode" unique="false" eType="//SeriesValuesDrawingMode"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minValue" unique="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxValue" unique="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectSeriesValue">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" containment="true" resolveProxies="false">
      <eType xsi:type="ecore:EClass" href="http://g5.1c.ru/v8/dt/mcore#//Value"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" unique="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="seriesId" unique="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Point">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="objectID" unique="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="x" unique="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="y" unique="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LayerObject" abstract="true">
    <eOperations name="setBounds" unique="false">
      <eParameters name="xMin" unique="false">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      </eParameters>
      <eParameters name="yMin" unique="false">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      </eParameters>
      <eParameters name="xMax" unique="false">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      </eParameters>
      <eParameters name="yMax" unique="false">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="objectID" unique="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="color" containment="true" resolveProxies="false">
      <eType xsi:type="ecore:EClass" href="http://g5.1c.ru/v8/dt/mcore#//Color"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" containment="true" resolveProxies="false">
      <eType xsi:type="ecore:EClass" href="http://g5.1c.ru/v8/dt/mcore#//Value"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="objectSeriesValues" upperBound="-1" eType="//ObjectSeriesValue" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tooltip" unique="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="showLinkedData" unique="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visible" unique="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="xMin" unique="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="yMin" unique="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="xMax" unique="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="yMax" unique="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PointShape" abstract="true" eSuperTypes="//LayerObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="font" containment="true" resolveProxies="false">
      <eType xsi:type="ecore:EClass" href="http://g5.1c.ru/v8/dt/mcore#//Font"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="picture" containment="true" resolveProxies="false">
      <eType xsi:type="ecore:EClass" href="http://g5.1c.ru/v8/dt/mcore#//Picture"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="symbol" unique="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="markerType" unique="false" eType="//MarkerType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pointPosition" unique="false" eType="//PaintingReferencePointPosition"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="drawingType" unique="false" eType="//PointObjectDrawingType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SinglePointShape" eSuperTypes="//PointShape">
    <eOperations name="contains" unique="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eParameters name="x" unique="false">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      </eParameters>
      <eParameters name="y" unique="false">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      </eParameters>
    </eOperations>
    <eOperations name="getIntCoordinates" unique="false" upperBound="-1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eParameters name="xShift" unique="false">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      </eParameters>
      <eParameters name="yShift" unique="false">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      </eParameters>
      <eParameters name="mult" unique="false">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="x" unique="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="y" unique="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MultiPointShape" eSuperTypes="//PointShape">
    <eStructuralFeatures xsi:type="ecore:EReference" name="points" upperBound="-1" eType="//Point" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LineStyle">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lineType" unique="false" eType="//LineType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="width" unique="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="gap" unique="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PointContour">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="objectID" unique="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="points" upperBound="-1" eType="//Point" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PolylineShape" eSuperTypes="//LayerObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="lineStyle" eType="//LineStyle" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="segments" upperBound="-1" eType="//PointContour" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PolygonShape" eSuperTypes="//LayerObject">
    <eOperations name="getFillColor" unique="false">
      <eType xsi:type="ecore:EClass" href="http://g5.1c.ru/v8/dt/mcore#//Color"/>
    </eOperations>
    <eOperations name="setFillColor" unique="false">
      <eParameters name="fillColor" unique="false">
        <eType xsi:type="ecore:EClass" href="http://g5.1c.ru/v8/dt/mcore#//Color"/>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="borderColor" containment="true" resolveProxies="false">
      <eType xsi:type="ecore:EClass" href="http://g5.1c.ru/v8/dt/mcore#//Color"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contours" upperBound="-1" eType="//PointContour" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LayerItem">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="objectID" unique="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="coordinateSystem" eType="//ShapeCoordinateSystemInfo" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="series" upperBound="-1" eType="//DataSeriesItem" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="objects" upperBound="-1" eType="//LayerObject" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" unique="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" unique="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataSourceRange" unique="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="xMin" unique="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="yMin" unique="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="xMax" unique="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="yMax" unique="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visible" unique="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="selectable" unique="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="scaleRangeBegin" unique="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="scaleRangeEnd" unique="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="organizationType" unique="false" eType="//DataSourceOrganizationType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="elementsType" unique="false">
      <eType xsi:type="ecore:EDataType" href="http://g5.1c.ru/v8/dt/mcore#//Uuid"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LegendItem">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="objectID" unique="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sampleTextColor" containment="true" resolveProxies="false">
      <eType xsi:type="ecore:EClass" href="http://g5.1c.ru/v8/dt/mcore#//Color"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sampleTextFont" containment="true" resolveProxies="false">
      <eType xsi:type="ecore:EClass" href="http://g5.1c.ru/v8/dt/mcore#//Font"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="picture" containment="true" resolveProxies="false">
      <eType xsi:type="ecore:EClass" href="http://g5.1c.ru/v8/dt/mcore#//Picture"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataSeriesID" unique="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="layerItemID" unique="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sampleText" unique="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="captionText" unique="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="showScaleType" unique="false" eType="//LegendItemShowScaleType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GeographicalSchemaComponent" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="border" containment="true" resolveProxies="false">
      <eType xsi:type="ecore:EClass" href="http://g5.1c.ru/v8/dt/mcore#//Border"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="transparent" unique="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="leftCoordinatePercentage" unique="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="topCoordinatePercentage" unique="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rightCoordinatePercentage" unique="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bottomCoordinatePercentage" unique="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GeographicalSchemaLegend" eSuperTypes="//GeographicalSchemaComponent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="scaleLineTextColor" containment="true" resolveProxies="false">
      <eType xsi:type="ecore:EClass" href="http://g5.1c.ru/v8/dt/mcore#//Color"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="borderColor" containment="true" resolveProxies="false">
      <eType xsi:type="ecore:EClass" href="http://g5.1c.ru/v8/dt/mcore#//Color"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="backColor" containment="true" resolveProxies="false">
      <eType xsi:type="ecore:EClass" href="http://g5.1c.ru/v8/dt/mcore#//Color"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="scaleLineTextFont" containment="true" resolveProxies="false">
      <eType xsi:type="ecore:EClass" href="http://g5.1c.ru/v8/dt/mcore#//Font"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="items" upperBound="-1" eType="//LegendItem" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="shown" unique="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="scaleLineShown" unique="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GeographicalSchemaDrawingArea" eSuperTypes="//GeographicalSchemaComponent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="borderColor" containment="true" resolveProxies="false">
      <eType xsi:type="ecore:EClass" href="http://g5.1c.ru/v8/dt/mcore#//Color"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="backColor" containment="true" resolveProxies="false">
      <eType xsi:type="ecore:EClass" href="http://g5.1c.ru/v8/dt/mcore#//Color"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GeographicalSchemaTitle" eSuperTypes="//GeographicalSchemaComponent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="font" containment="true" resolveProxies="false">
      <eType xsi:type="ecore:EClass" href="http://g5.1c.ru/v8/dt/mcore#//Font"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="text" upperBound="-1" containment="true" resolveProxies="false">
      <eType xsi:type="ecore:EClass" href="http://g5.1c.ru/v8/dt/mcore#//LocalStringMapEntry"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="textColor" containment="true" resolveProxies="false">
      <eType xsi:type="ecore:EClass" href="http://g5.1c.ru/v8/dt/mcore#//Color"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="borderColor" containment="true" resolveProxies="false">
      <eType xsi:type="ecore:EClass" href="http://g5.1c.ru/v8/dt/mcore#//Color"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="backColor" containment="true" resolveProxies="false">
      <eType xsi:type="ecore:EClass" href="http://g5.1c.ru/v8/dt/mcore#//Color"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="shown" unique="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="align" unique="false" eType="//HorizontalAlign"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PrintOption" instanceClassName="java.util.Map$Entry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" unique="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" containment="true" resolveProxies="false">
      <eType xsi:type="ecore:EClass" href="http://g5.1c.ru/v8/dt/mcore#//Value"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GeographicalSchema">
    <eSuperTypes href="http://g5.1c.ru/v8/dt/metadata/mdclass#//AbstractGeographicalSchema"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="layerItems" upperBound="-1" eType="//LayerItem" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="printOptions" upperBound="-1" eType="//PrintOption" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="geographicalSchemaLegend" eType="//GeographicalSchemaLegend" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="geographicalSchemaTitle" eType="//GeographicalSchemaTitle" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="geographicalSchemaDrawingArea" eType="//GeographicalSchemaDrawingArea" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="latitudeShift" unique="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="longitudeShift" unique="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="schemaProjection" unique="false" eType="//Projection"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="showMode" unique="false" eType="//ShowMode"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="scale" unique="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="xMin" unique="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="yMin" unique="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="xMax" unique="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="yMax" unique="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="viewedXMin" unique="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="viewedYMin" unique="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="viewedXMax" unique="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="viewedYMax" unique="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="useOutput" unique="false" eType="//UseOutput"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="currentID" unique="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GeoPicture">
    <eSuperTypes href="http://g5.1c.ru/v8/dt/mcore#//PictureDef"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="content" unique="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ShowMode">
    <eLiterals name="ScaleDefined"/>
    <eLiterals name="AllData"/>
    <eLiterals name="SpecifiedArea"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="LineType">
    <eLiterals name="None"/>
    <eLiterals name="Solid"/>
    <eLiterals name="Dashed"/>
    <eLiterals name="Dotted"/>
    <eLiterals name="DashDotted"/>
    <eLiterals name="DashDottedDotted"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Projection">
    <eLiterals name="CylindricalMillerProjection"/>
    <eLiterals name="CylindricalLambertEqualAreaProjection"/>
    <eLiterals name="CylindricalGallStereographicProjection"/>
    <eLiterals name="CylindricalEquidistantProjection"/>
    <eLiterals name="PseudoCylindricalSinusoidalProjection"/>
    <eLiterals name="PseudoCylindricalMollweideProjection"/>
    <eLiterals name="PseudoCylindricalRobinsonProjection"/>
    <eLiterals name="PseudoCylindricalEckert1Projection"/>
    <eLiterals name="PseudoCylindricalEckert2Projection"/>
    <eLiterals name="PseudoCylindricalEckert3Projection"/>
    <eLiterals name="PseudoCylindricalEckert4Projection"/>
    <eLiterals name="PseudoCylindricalEckert5Projection"/>
    <eLiterals name="PseudoCylindricalEckert6Projection"/>
    <eLiterals name="PseudoCylindricalHatanoAsymetricalEqualAreaProjection"/>
    <eLiterals name="PseudoCylindricalLoximutalProjection"/>
    <eLiterals name="PseudoCylindricalMcBrydeThomasFlatPolarParabolicProjection"/>
    <eLiterals name="PseudoCylindricalMcBrydeThomasFlatPolarQuarticProjection"/>
    <eLiterals name="PseudoCylindricalMcBrydeThomasFlatPolarSinusoidalProjection"/>
    <eLiterals name="PseudoCylindricalPutninP2Projection"/>
    <eLiterals name="PseudoCylindricalPutninP5Projection"/>
    <eLiterals name="PseudoCylindricalWinkel1Projection"/>
    <eLiterals name="PseudoCylindricalBoggsEumorphicProjection"/>
    <eLiterals name="AzimuthalHammerProjection"/>
    <eLiterals name="AzimuthalWagner7Projection"/>
    <eLiterals name="AzimuthalAitoffProjection"/>
    <eLiterals name="AzimuthalWinkelTripelProjection"/>
    <eLiterals name="AzimuthalEquidistantProjection"/>
    <eLiterals name="AzimuthalLambertEqualAreaProjection"/>
    <eLiterals name="MiscellaneousAugustEpicycloidalProjection"/>
    <eLiterals name="MiscellaneousBaconGlobularProjection"/>
    <eLiterals name="MiscellaneousNicolosiGlobularProjection"/>
    <eLiterals name="MiscellaneousApianGlobular1Projection"/>
    <eLiterals name="MiscellaneousOrteliusOvalProjection"/>
    <eLiterals name="MiscellaneousVanDerGrinten1Projection"/>
    <eLiterals name="MiscellaneousVanDerGrinten2Projection"/>
    <eLiterals name="MiscellaneousVanDerGrinten3Projection"/>
    <eLiterals name="ConicLambertEqualAreaProjection"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DataSourceOrganizationType">
    <eLiterals name="AtRow"/>
    <eLiterals name="AtIntersection"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="LayerSeriesShowMode">
    <eLiterals name="DontShow"/>
    <eLiterals name="Text"/>
    <eLiterals name="Column"/>
    <eLiterals name="ShapeSize"/>
    <eLiterals name="ShapeColor"/>
    <eLiterals name="ShapeColorHue"/>
    <eLiterals name="Picture"/>
    <eLiterals name="Pie"/>
    <eLiterals name="SizedPie"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SeriesValuesDrawingMode">
    <eLiterals name="ShowAsValue"/>
    <eLiterals name="ShowAsPart"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="MarkerType">
    <eLiterals name="None"/>
    <eLiterals name="Pin"/>
    <eLiterals name="Darts"/>
    <eLiterals name="LittleCircle"/>
    <eLiterals name="BigCircle"/>
    <eLiterals name="LittleSquare"/>
    <eLiterals name="BigSquare"/>
    <eLiterals name="LittleTriangle"/>
    <eLiterals name="BigTriangle"/>
    <eLiterals name="QuestionMark"/>
    <eLiterals name="ExclamationPoint"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PaintingReferencePointPosition">
    <eLiterals name="LeftTop"/>
    <eLiterals name="LeftCenter"/>
    <eLiterals name="LeftBottom"/>
    <eLiterals name="CenterTop"/>
    <eLiterals name="Center"/>
    <eLiterals name="CenterBottom"/>
    <eLiterals name="RightTop"/>
    <eLiterals name="RightCenter"/>
    <eLiterals name="RightBottom"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PointObjectDrawingType">
    <eLiterals name="Char"/>
    <eLiterals name="Marker"/>
    <eLiterals name="Picture"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="LegendItemShowScaleType">
    <eLiterals name="DoNotShow"/>
    <eLiterals name="ShowByValues"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="HorizontalAlign">
    <eLiterals name="Middle"/>
    <eLiterals name="Left"/>
    <eLiterals name="Right"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="UseOutput">
    <eLiterals name="Auto"/>
    <eLiterals name="Enable"/>
    <eLiterals name="Disable"/>
  </eClassifiers>
</ecore:EPackage>
