<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="externalProperties" nsURI="http://g5.1c.ru/v8/dt/metadata/externalProperties" nsPrefix="mdExternalProperties">
  <eClassifiers xsi:type="ecore:EClass" name="AbstractAdditionalIndexes"/>
  <eClassifiers xsi:type="ecore:EClass" name="AdditionalIndexesContainer" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="additionalIndexes" eType="//AbstractAdditionalIndexes" transient="true">
      <eAnnotations source="http://www.1c.ru/v8/dt/common/ExternalProperty"/>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
