<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="extension" nsURI="http://g5.1c.ru/v8/dt/metadata/mdclass/extension" nsPrefix="mdclassExtension">
  <eClassifiers xsi:type="ecore:EClass" name="MdObjectExtension">
    <eSuperTypes href="g5.1c.ru.v8.dt.metadata.mdclass.ecore#//ObjectExtension"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BasicCommandExtension" eSuperTypes="//MdObjectExtension">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="group" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="commandParameterType" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="commandModule" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="picture" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BasicFormExtension" eSuperTypes="//MdObjectExtension">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="form" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BasicFeatureExtension" eSuperTypes="//MdObjectExtension">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BasicTabularSectionExtension" eSuperTypes="//MdObjectExtension"/>
  <eClassifiers xsi:type="ecore:EClass" name="BasicTemplateExtension" eSuperTypes="//MdObjectExtension">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="template" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BasicDbObjectExtension" abstract="true" eSuperTypes="//MdObjectExtension">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="objectModule" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="managerModule" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RoleExtension" eSuperTypes="//MdObjectExtension">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rights" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LanguageExtension" eSuperTypes="//MdObjectExtension">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="languageCode" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SessionParameterExtension" eSuperTypes="//MdObjectExtension">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CommonModuleExtension" eSuperTypes="//MdObjectExtension">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="module" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="global" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="clientManagedApplication" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="server" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="externalConnection" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serverCall" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="returnValuesReuse" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CommonAttributeExtension" eSuperTypes="//BasicFeatureExtension">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="content" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="autoUse" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataSeparation" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="separatedDataUse" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CommonFormExtension" eSuperTypes="//BasicFormExtension"/>
  <eClassifiers xsi:type="ecore:EClass" name="CommonPictureExtension" eSuperTypes="//MdObjectExtension"/>
  <eClassifiers xsi:type="ecore:EClass" name="CommandGroupExtension" eSuperTypes="//MdObjectExtension">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="picture" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="category" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CatalogExtension" eSuperTypes="//BasicDbObjectExtension">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hierarchical" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hierarchyType" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="owners" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="codeLength" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="descriptionLength" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="codeType" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="codeAllowedLength" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="predefined" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultObjectForm" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultFolderForm" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultListForm" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultChoiceForm" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultFolderChoiceForm" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DocumentExtension" eSuperTypes="//BasicDbObjectExtension">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberType" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberLength" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberAllowedLength" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultObjectForm" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultListForm" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultChoiceForm" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="registerRecords" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DocumentNumeratorExtension" eSuperTypes="//MdObjectExtension">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberType" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberLength" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberAllowedLength" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ChartOfCharacteristicTypesExtension" eSuperTypes="//BasicDbObjectExtension">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hierarchical" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="codeLength" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="codeAllowedLength" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="descriptionLength" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="predefined" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultObjectForm" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultFolderForm" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultListForm" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultChoiceForm" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultFolderChoiceForm" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnumExtension" eSuperTypes="//MdObjectExtension">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultListForm" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultChoiceForm" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="managerModule" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InformationRegisterExtension" eSuperTypes="//MdObjectExtension">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="informationRegisterPeriodicity" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="writeMode" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="recordSetModule" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="managerModule" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultRecordForm" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultListForm" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConfigurationExtension" eSuperTypes="//MdObjectExtension">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultRunMode" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="usePurposes" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="managedApplicationModule" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sessionModule" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="externalConnectionModule" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="commandInterface" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="homePageWorkArea" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mainSectionCommandInterface" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultLanguage" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultReportForm" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultReportSettingsForm" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultReportVariantForm" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultDynamicListSettingsForm" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultSearchForm" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultDataHistoryChangeHistoryForm" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultDataHistoryVersionDataForm" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultDataHistoryVersionDifferencesForm" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="modalityUseMode" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="synchronousExtensionAndAddInCallUseMode" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="interfaceCompatibilityMode" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="compatibilityMode" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultStyle" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mainSectionPicture" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="logo" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="splash" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StyleItemExtension" eSuperTypes="//MdObjectExtension">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExchangePlanExtension" eSuperTypes="//BasicDbObjectExtension">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="content" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultObjectForm" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultListForm" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultChoiceForm" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExchangePlanContentItemExtension">
    <eSuperTypes href="g5.1c.ru.v8.dt.metadata.mdclass.ecore#//ObjectExtension"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mdObject" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mdObjectIncluded" unique="false" defaultValueLiteral="true">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SubsystemExtension" eSuperTypes="//MdObjectExtension">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="commandInterface" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="picture" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WSReferenceExtension" eSuperTypes="//MdObjectExtension"/>
  <eClassifiers xsi:type="ecore:EClass" name="EventSubscriptionExtension" eSuperTypes="//MdObjectExtension"/>
  <eClassifiers xsi:type="ecore:EClass" name="DefinedTypeExtension" eSuperTypes="//MdObjectExtension">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConstantExtension" eSuperTypes="//MdObjectExtension">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultForm" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valueManagerModule" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SequenceExtension" eSuperTypes="//MdObjectExtension">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="recordSetModule" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SequenceDimensionExtension" eSuperTypes="//MdObjectExtension">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DocumentJournalExtension" eSuperTypes="//MdObjectExtension">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="registeredDocuments" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="managerModule" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultForm" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReportExtension" eSuperTypes="//MdObjectExtension">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mainDataCompositionSchema" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="objectModule" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="managerModule" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultForm" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultSettingsForm" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultVariantForm" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataProcessorExtension" eSuperTypes="//MdObjectExtension">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultForm" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="objectModule" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="managerModule" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AccumulationRegisterExtension" eSuperTypes="//MdObjectExtension">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="registerType" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="recordSetModule" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="managerModule" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultListForm" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionalOptionExtension" eSuperTypes="//MdObjectExtension">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="location" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BusinessProcessExtension" eSuperTypes="//BasicDbObjectExtension">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberLength" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberAllowedLength" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="task" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultObjectForm" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultListForm" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultChoiceForm" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TaskExtension" eSuperTypes="//BasicDbObjectExtension">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberLength" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberAllowedLength" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="descriptionLength" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultObjectForm" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultListForm" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultChoiceForm" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ScheduledJobExtension" eSuperTypes="//MdObjectExtension"/>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionalOptionsParameterExtension" eSuperTypes="//MdObjectExtension"/>
  <eClassifiers xsi:type="ecore:EClass" name="FilterCriterionExtension" eSuperTypes="//MdObjectExtension">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="content" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultForm" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="managerModule" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SettingsStorageExtension" eSuperTypes="//MdObjectExtension">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="managerModule" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultSaveForm" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultLoadForm" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XDTOPackageExtension" eSuperTypes="//MdObjectExtension">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="package" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WebServiceExtension" eSuperTypes="//MdObjectExtension">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="module" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HTTPServiceExtension" eSuperTypes="//MdObjectExtension">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="module" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExternalDataSourceExtension" eSuperTypes="//MdObjectExtension"/>
  <eClassifiers xsi:type="ecore:EClass" name="TableExtension" eSuperTypes="//MdObjectExtension">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tableType" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tableDataType" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="keyFields" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="objectModule" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="recordSetModule" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="managerModule" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultObjectForm" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultRecordForm" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultListForm" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultChoiceForm" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FieldExtension" eSuperTypes="//MdObjectExtension">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CubeExtension" eSuperTypes="//MdObjectExtension">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="recordSetModule" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="managerModule" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultRecordForm" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultListForm" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DimensionTableExtension" eSuperTypes="//MdObjectExtension">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="objectModule" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="managerModule" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultObjectForm" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultListForm" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultChoiceForm" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DimensionExtension" eSuperTypes="//MdObjectExtension">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ResourceExtension" eSuperTypes="//MdObjectExtension">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionExtension" eSuperTypes="//MdObjectExtension">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ChartOfAccountsExtension" eSuperTypes="//BasicDbObjectExtension">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="codeLength" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="descriptionLength" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="predefined" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="extDimensionTypes" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxExtDimensionCount" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultObjectForm" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultListForm" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultChoiceForm" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ChartOfCalculationTypesExtension" eSuperTypes="//BasicDbObjectExtension">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="codeLength" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="descriptionLength" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="codeType" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="codeAllowedLength" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="predefined" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dependenceOnCalculationTypes" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="actionPeriodUse" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultObjectForm" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultListForm" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultChoiceForm" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AccountingRegisterExtension" eSuperTypes="//MdObjectExtension">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="chartOfAccounts" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="correspondence" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="periodAdjustmentLength" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="recordSetModule" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="managerModule" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultListForm" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AccountingRegisterDimensionExtension" eSuperTypes="//BasicFeatureExtension">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="balance" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CalculationRegisterExtension" eSuperTypes="//MdObjectExtension">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="actionPeriod" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="basePeriod" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="schedule" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="recordSetModule" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="managerModule" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultListForm" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StyleExtension" eSuperTypes="//MdObjectExtension">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="style" unique="false">
      <eType xsi:type="ecore:EEnum" href="http://g5.1c.ru/v8/dt/metadata/mdclass/extension/type#//MdPropertyState"/>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
