<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="model" nsURI="http://g5.1c.ru/v8/dt/scc" nsPrefix="scc">
  <eClassifiers xsi:type="ecore:EClass" name="StandaloneContent">
    <eSuperTypes href="g5.1c.ru.v8.dt.metadata.mdclass.ecore#//AbstractStandaloneContent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="usedItem" upperBound="-1" eType="//StandaloneContentUsedItem" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="unusedItem" upperBound="-1" eType="//StandaloneContentUnusedItem" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="priorityItem" upperBound="-1" eType="//StandaloneContentPriorityItem" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataExchangeSettings" eType="//StandaloneContentDataExchangeSettings" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StandaloneContentMdObjectAware" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="metadata">
      <eType xsi:type="ecore:EClass" href="g5.1c.ru.v8.dt.metadata.mdclass.ecore#//MdObject"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StandaloneContentUsedItem" eSuperTypes="//StandaloneContentMdObjectAware">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="priority" unique="false" eType="//StandaloneContentItemPriority"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StandaloneContentUnusedItem" eSuperTypes="//StandaloneContentMdObjectAware"/>
  <eClassifiers xsi:type="ecore:EClass" name="StandaloneContentPriorityItem" eSuperTypes="//StandaloneContentMdObjectAware">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="priority" unique="false" eType="//StandaloneContentItemPriority"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StandaloneContentDataExchangeSettings">
    <eStructuralFeatures xsi:type="ecore:EReference" name="exchangePlan">
      <eType xsi:type="ecore:EClass" href="g5.1c.ru.v8.dt.metadata.mdclass.ecore#//MdObject"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="exchangeOnChangeData" unique="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="exchangePeriod" unique="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="transactionCount" unique="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="inactiveNodesCleanupTimeout" unique="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="noCodeCorrections" upperBound="-1">
      <eType xsi:type="ecore:EClass" href="g5.1c.ru.v8.dt.metadata.mdclass.ecore#//MdObject"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="StandaloneContentItemPriority">
    <eLiterals name="Default"/>
    <eLiterals name="MainServer" value="1"/>
    <eLiterals name="LocalServer" value="2"/>
  </eClassifiers>
</ecore:EPackage>
