<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="model" nsURI="http://g5.1c.ru/v8/dt/scc" nsPrefix="scc">
  <eClassifiers xsi:type="ecore:EClass" name="StandaloneContent">
    <eSuperTypes href="g5.1c.ru.v8.dt.metadata.mdclass.ecore#//AbstractStandaloneContent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="usedItem" upperBound="-1" eType="//StandaloneContentUsedItem" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="unusedItem" upperBound="-1" eType="//StandaloneContentUnusedItem" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StandaloneContentUsedItem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="metadata">
      <eType xsi:type="ecore:EClass" href="g5.1c.ru.v8.dt.metadata.mdclass.ecore#//MdObject"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="priority" unique="false" eType="//StandaloneContentItemPriority"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StandaloneContentUnusedItem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="metadata">
      <eType xsi:type="ecore:EClass" href="g5.1c.ru.v8.dt.metadata.mdclass.ecore#//MdObject"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="StandaloneContentItemPriority">
    <eLiterals name="Default"/>
    <eLiterals name="MainServer" value="1"/>
    <eLiterals name="LocalServer" value="2"/>
  </eClassifiers>
</ecore:EPackage>
