<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="model" nsURI="http://g5.1c.ru/v8/dt/hpwa" nsPrefix="hpwa">
  <eClassifiers xsi:type="ecore:EClass" name="HomePageWorkArea">
    <eSuperTypes href="http://g5.1c.ru/v8/dt/metadata/mdclass#//AbstractWorkArea"/>
    <eOperations name="validate" unique="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eParameters name="diagnostics" unique="false">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain"/>
      </eParameters>
      <eParameters name="context" unique="false">
        <eGenericType>
          <eTypeArguments>
            <eClassifier xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
          </eTypeArguments>
          <eTypeArguments>
            <eClassifier xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
          </eTypeArguments>
          <eClassifier xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EMap"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="workingAreaTemplate" unique="false" eType="//WorkingAreaTemplate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mACommandInterfaceDisplays" unique="false" eType="//MACommandInterfaceDisplays"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="columns" upperBound="-1" eType="//HomePageWorkAreaColumn" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HomePageWorkAreaColumnItem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="form">
      <eType xsi:type="ecore:EClass" href="http://g5.1c.ru/v8/dt/metadata/mdclass#//BasicForm"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="height" unique="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="visibility" containment="true" resolveProxies="false">
      <eType xsi:type="ecore:EClass" href="http://g5.1c.ru/v8/dt/metadata/mdclass#//AdjustableBoolean"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HomePageWorkAreaColumn">
    <eStructuralFeatures xsi:type="ecore:EReference" name="items" upperBound="-1" eType="//HomePageWorkAreaColumnItem" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="MACommandInterfaceDisplays">
    <eLiterals name="None"/>
    <eLiterals name="Top" value="1"/>
    <eLiterals name="Bottom" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="WorkingAreaTemplate">
    <eLiterals name="OneColumn"/>
    <eLiterals name="TwoColumnsEqualWidth" value="1"/>
    <eLiterals name="TwoColumnsVariableWidth" value="2"/>
  </eClassifiers>
</ecore:EPackage>
