<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="model" nsURI="http://g5.1c.ru/v8/dt/ws/wsdefinitions" nsPrefix="wsdefinitions">
  <eClassifiers xsi:type="ecore:EClass" name="WSDefinitions">
    <eStructuralFeatures xsi:type="ecore:EReference" name="model" containment="true" resolveProxies="false">
      <eType xsi:type="ecore:EClass" href="http://g5.1c.ru/v8/dt/xdto/model#//InnerModel"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="services" upperBound="-1" eType="//Service" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="documentation" unique="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Service">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="namespace" unique="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" unique="false" eType="//NCName"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="endpoints" upperBound="-1" eType="//Endpoint" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="documentation" unique="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Endpoint">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" unique="false" eType="//NCName"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operations" lowerBound="1" upperBound="-1" eType="//Operation" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="documentation" unique="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="soap" unique="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Operation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" unique="false" eType="//NCName"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="documentation" unique="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="retValNillable" unique="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="retValDoc" unique="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="retValType" containment="true" resolveProxies="false">
      <eType xsi:type="ecore:EClass" href="g5.1c.ru.v8.dt.mcore.ecore#//QName"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1" eType="//Parameter" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parameter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" unique="false" eType="//NCName"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" containment="true" resolveProxies="false">
      <eType xsi:type="ecore:EClass" href="g5.1c.ru.v8.dt.mcore.ecore#//QName"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="direction" unique="false" eType="//Direction"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nillable" unique="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="documentation" unique="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Direction">
    <eLiterals name="In"/>
    <eLiterals name="Out" value="1"/>
    <eLiterals name="InOut" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="NCName" instanceClassName="java.lang.String"/>
</ecore:EPackage>
